"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import FileUpload from "@/components/FileUpload";
import ReactMarkdown from "react-markdown";
import toast from "react-hot-toast";
import { HiOutlineSparkles, HiOutlineLockClosed } from "react-icons/hi2";
import ActionButtons from "@/components/ActionButtons";
import OutputContainer from "@/components/OutputContainer";

export default function GenerateDocsPage() {
  const [doc, setDoc] = useState(null);
  const [error, setError] = useState("");
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [includeAudit, setIncludeAudit] = useState(false);
  const [showLoginModal, setShowLoginModal] = useState(false);

  const handleExportMarkdown = () => {
    if (!doc?._id) return;
    window.open(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/api/docs/export/${doc._id}/markdown`, '_blank');
  };

  const handleDownloadPdf = async () => {
    if (!doc) return;
    setIsGeneratingPdf(true);
    try {
      const html2pdf = (await import('html2pdf.js')).default;
      const element = document.getElementById('pdf-export-container');
      
      const opt = {
        margin: [20, 15, 20, 15],
        filename: 'QuillStack_Documentation.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
      };

      const worker = html2pdf().from(element).set(opt);
      await worker.toPdf().get('pdf').then((pdf) => {
        const totalPages = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          pdf.setFontSize(10);
          pdf.setTextColor(100);
          
          pdf.text('QuillStack AI Documentation', 15, 12);
          
          pdf.setDrawColor(200);
          pdf.setLineWidth(0.5);
          pdf.line(15, 15, pdf.internal.pageSize.getWidth() - 15, 15);

          pdf.line(15, pdf.internal.pageSize.getHeight() - 15, pdf.internal.pageSize.getWidth() - 15, pdf.internal.pageSize.getHeight() - 15);

          pdf.text('Generated by QuillStack AI', 15, pdf.internal.pageSize.getHeight() - 10);
          pdf.text(`Page ${i} of ${totalPages}`, pdf.internal.pageSize.getWidth() - 35, pdf.internal.pageSize.getHeight() - 10);
        }
      });
      await worker.save();
      
      toast.success("PDF Downloaded Successfully");
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("Failed to generate PDF");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleCopy = () => {
    if (!doc) return;
    const textToCopy = doc.content || doc;
    navigator.clipboard.writeText(textToCopy)
      .then(() => toast.success("Copied to clipboard!"))
      .catch(() => toast.error("Failed to copy"));
  };

  const handleShare = async () => {
    if (!doc?._id) return;
    const shareUrl = `${window.location.origin}/doc/${doc._id}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'QuillStack AI Documentation',
          text: `Check out the documentation for ${doc.filename || 'this file'}`,
          url: shareUrl,
        });
        return;
      } catch (err) {
        if (err.name === "AbortError") return;
        console.error("Share failed", err);
      }
    }
    
    navigator.clipboard.writeText(shareUrl)
      .then(() => toast.success("Share link copied to clipboard!"))
      .catch(() => toast.error("Failed to copy link"));
  };

  return (
    <div className="min-h-screen bg-[#060910] text-[#F8FAFC] selection:bg-accent-primary/20 pt-32 pb-20 px-6 bg-mesh">
      <div className="max-w-7xl mx-auto flex flex-col lg:flex-row gap-12 items-start">
        
        {/* Left Panel */}
        <motion.div
          className="w-full lg:w-1/3 space-y-8 lg:sticky lg:top-32"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
        >
          <div className="space-y-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-accent-primary/10 border border-accent-primary/20 text-xs font-bold text-accent-primary uppercase tracking-widest"
            >
              <HiOutlineSparkles />
              <span>AI Engine Active</span>
            </motion.div>
            <h1 className="text-4xl font-extrabold tracking-tight">
              Generate <span className="text-gradient">Docs.</span>
            </h1>
            <p className="text-gray-400 leading-relaxed">
              Upload your source code and let our AI architect map out your project's logic and structure.
            </p>
          </div>

          <div className="space-y-6">
            <div className="glass p-6 rounded-3xl border-white/5 flex items-center justify-between">
              <div className="space-y-0.5">
                <p className="text-sm font-bold text-white">Security & Performance Audit</p>
                <p className="text-[10px] text-gray-500">Enable deep AI logic scan</p>
              </div>
              <button 
                onClick={() => setIncludeAudit(!includeAudit)}
                className={`w-12 h-6 rounded-full transition-colors relative ${includeAudit ? 'bg-accent-primary' : 'bg-white/10'}`}
              >
                <motion.div 
                  animate={{ x: includeAudit ? 26 : 2 }}
                  className="absolute top-1 left-0 w-4 h-4 rounded-full bg-white shadow-xl"
                />
              </button>
            </div>

            <FileUpload 
              onUploadSuccess={setDoc} 
              includeAudit={includeAudit} 
              onRequestLogin={() => setShowLoginModal(true)}
            />
          </div>
          
          <AnimatePresence>
            {error && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="p-4 bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-2xl flex items-center gap-3"
              >
                <div className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
                {error}
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>

        {/* Right Panel */}
        <motion.div
          className="w-full lg:w-2/3 space-y-6"
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.1 }}
        >
          <div className="glass rounded-3xl border-white/5 overflow-hidden flex flex-col min-h-[600px]">
            <div className="p-4 border-b border-white/5 bg-white/5 backdrop-blur-md">
              <ActionButtons 
                doc={doc}
                isGeneratingPdf={isGeneratingPdf}
                onExportMarkdown={handleExportMarkdown}
                onDownloadPdf={handleDownloadPdf}
                onCopy={handleCopy}
                onShare={handleShare}
                onGenerateNew={() => setDoc(null)}
              />
            </div>
            <div className="flex-1 p-0 overflow-y-auto">
              <OutputContainer doc={doc} />
            </div>
          </div>
        </motion.div>
      </div>

      {doc && (
        <div style={{ position: 'absolute', top: '-9999px', left: '-9999px', width: '800px', backgroundColor: 'white' }}>
          <div id="pdf-export-container" className="pdf-markdown-content" style={{ fontFamily: 'Arial, Helvetica, sans-serif', padding: '10px 20px', backgroundColor: 'white', color: '#1f2937' }}>
            <style dangerouslySetInnerHTML={{
              __html: `
                .pdf-markdown-content { background-color: white !important; color: #1f2937 !important; }
                .pdf-markdown-content h1 { color: #8A4FFF !important; font-size: 2rem !important; font-weight: 700 !important; margin-bottom: 20px !important; margin-top: 24px !important; border-bottom: 2px solid #8A4FFF !important; padding-bottom: 8px !important; page-break-after: avoid; }
                .pdf-markdown-content h2 { color: #6d28d9 !important; font-size: 1.5rem !important; font-weight: 700 !important; margin-bottom: 16px !important; margin-top: 24px !important; page-break-after: avoid; }
                .pdf-markdown-content h3 { color: #374151 !important; font-size: 1.25rem !important; font-weight: 600 !important; margin-bottom: 12px !important; margin-top: 20px !important; page-break-after: avoid; }
                .pdf-markdown-content p { font-size: 11pt !important; line-height: 1.6 !important; color: #374151 !important; margin-bottom: 16px !important; }
                .pdf-markdown-content ul, .pdf-markdown-content ol { margin-bottom: 16px !important; padding-left: 24px !important; }
                .pdf-markdown-content li { font-size: 11pt !important; line-height: 1.6 !important; color: #374151 !important; margin-bottom: 6px !important; }
                .pdf-markdown-content pre { background-color: #f3f4f6 !important; border: 1px solid #d1d5db !important; border-radius: 8px !important; padding: 16px !important; margin: 20px 0 !important; page-break-inside: avoid !important; white-space: pre-wrap !important; word-wrap: break-word !important; }
                .pdf-markdown-content code { color: #047857 !important; font-family: 'Courier New', Courier, monospace !important; font-size: 9.5pt !important; }
                .pdf-markdown-content table { width: 100% !important; border-collapse: collapse !important; margin: 20px 0 !important; page-break-inside: avoid !important; }
                .pdf-markdown-content th, .pdf-markdown-content td { border: 1px solid #d1d5db !important; padding: 12px !important; text-align: left !important; }
                .pdf-markdown-content th { background-color: #f3f4f6 !important; color: #374151 !important; font-weight: 700 !important; }
                .pdf-markdown-content blockquote { border-left: 4px solid #8A4FFF !important; padding-left: 16px !important; color: #4b5563 !important; font-style: italic !important; background-color: #f9fafb !important; padding: 16px !important; margin: 20px 0 !important; page-break-inside: avoid !important; }
              `
            }} />
            <ReactMarkdown>{doc.content || doc}</ReactMarkdown>
          </div>
        </div>
      )}
      {/* Login Required Modal - Placed at root to escape stacking contexts */}
      <AnimatePresence>
        {showLoginModal && (
          <div className="fixed inset-0 z-[9999] flex items-center justify-center p-6">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/80 backdrop-blur-md"
              onClick={() => setShowLoginModal(false)}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-sm glass-dark p-8 rounded-3xl border border-white/10 shadow-2xl text-center space-y-6"
            >
              <div className="w-16 h-16 bg-accent-primary/10 rounded-2xl flex items-center justify-center mx-auto text-accent-primary">
                <HiOutlineLockClosed className="text-3xl" />
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold text-white uppercase tracking-tight">Authentication Required</h3>
                <p className="text-sm text-gray-400">Please sign in to your account to continue generating documentation.</p>
              </div>
              <div className="flex flex-col gap-3 pt-2">
                <button
                  onClick={() => window.location.href = '/login'}
                  className="w-full py-4 bg-accent-primary text-white rounded-2xl font-bold hover:scale-[1.02] shadow-xl shadow-accent-primary/20 transition-all active:scale-95"
                >
                  Sign In to Account
                </button>
                <button
                  onClick={() => setShowLoginModal(false)}
                  className="w-full py-4 bg-white/5 text-gray-400 rounded-2xl font-bold hover:bg-white/10 transition-all"
                >
                  Maybe Later
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
