"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import FileUpload from "@/components/FileUpload";
import ReactMarkdown from "react-markdown";
import toast from "react-hot-toast";
import ActionButtons from "@/components/ActionButtons";
import OutputContainer from "@/components/OutputContainer";

export default function GenerateDocsPage() {
  const [doc, setDoc] = useState(null);
  const [error, setError] = useState("");
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const handleExportMarkdown = () => {
    if (!doc?._id) return;
    window.open(`http://localhost:5000/api/docs/export/${doc._id}/markdown`, '_blank');
  };

  const handleDownloadPdf = async () => {
    if (!doc) return;
    setIsGeneratingPdf(true);
    try {
      const html2pdf = (await import('html2pdf.js')).default;
      const element = document.getElementById('pdf-export-container');
      
      const opt = {
        margin: [20, 15, 20, 15],
        filename: 'QuillStack_Documentation.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
      };

      const worker = html2pdf().from(element).set(opt);
      await worker.toPdf().get('pdf').then((pdf) => {
        const totalPages = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          pdf.setFontSize(10);
          pdf.setTextColor(100);
          
          pdf.text('QuillStack AI Documentation', 15, 12);
          
          pdf.setDrawColor(200);
          pdf.setLineWidth(0.5);
          pdf.line(15, 15, pdf.internal.pageSize.getWidth() - 15, 15);

          pdf.line(15, pdf.internal.pageSize.getHeight() - 15, pdf.internal.pageSize.getWidth() - 15, pdf.internal.pageSize.getHeight() - 15);

          pdf.text('Generated by QuillStack AI', 15, pdf.internal.pageSize.getHeight() - 10);
          pdf.text(`Page ${i} of ${totalPages}`, pdf.internal.pageSize.getWidth() - 35, pdf.internal.pageSize.getHeight() - 10);
        }
      });
      await worker.save();
      
      toast.success("PDF Downloaded Successfully");
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("Failed to generate PDF");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleCopy = () => {
    if (!doc) return;
    const textToCopy = doc.content || doc;
    navigator.clipboard.writeText(textToCopy)
      .then(() => toast.success("Copied to clipboard!"))
      .catch(() => toast.error("Failed to copy"));
  };

  const handleShare = async () => {
    if (!doc?._id) return;
    const shareUrl = `${window.location.origin}/doc/${doc._id}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'QuillStack AI Documentation',
          text: `Check out the documentation for ${doc.filename || 'this file'}`,
          url: shareUrl,
        });
        return;
      } catch (err) {
        if (err.name === "AbortError") return;
        console.error("Share failed", err);
      }
    }
    
    navigator.clipboard.writeText(shareUrl)
      .then(() => toast.success("Share link copied to clipboard!"))
      .catch(() => toast.error("Failed to copy link"));
  };

  return (
    <div className="min-h-screen bg-[#0B0F1C] relative overflow-hidden flex flex-col">
      {/* Animated fuchsia radial background */}
      <style dangerouslySetInnerHTML={{
        __html: `
          @keyframes flow-diagonal {
            0% { transform: translate(-20%, -20%) rotate(-25deg); opacity: 0.25; }
            50% { transform: translate(20%, -40%) rotate(-25deg); opacity: 0.4; }
            100% { transform: translate(-20%, -20%) rotate(-25deg); opacity: 0.25; }
          }
        `
      }} />
      <div className="pointer-events-none absolute inset-0 z-0">
        <div
          className="absolute left-0 top-1/4 w-[60vw] h-[40vw] max-w-2xl max-h-[30vh] rounded-full bg-fuchsia-700 opacity-30 blur-3xl rotate-[-25deg]"
          style={{ animation: "flow-diagonal 6s ease-in-out infinite" }}
        ></div>
      </div>

      {/* Two Panel Layout - Shifted up, Responsive Grid */}
      <div className="relative z-10 flex-1 flex flex-col lg:flex-row pt-24 pb-12 px-4 sm:px-6 lg:px-8 max-w-[1600px] mx-auto w-full gap-8 lg:gap-12 items-start justify-start">
        {/* Left Panel - Upload & Generate */}
        <motion.div
          className="w-full lg:w-4/12 flex flex-col justify-start"
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="w-full lg:sticky top-24">
            <motion.h1
              className="text-3xl sm:text-4xl font-extrabold text-white mb-3 tracking-tight drop-shadow"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1, duration: 0.5 }}
            >
              Generate <span className="text-[#8A4FFF]">Docs</span>
            </motion.h1>
            <motion.p
              className="text-base text-fuchsia-200/80 mb-8 max-w-sm"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.5 }}
            >
              Upload your code file to let <span className="text-fuchsia-400 font-semibold">QuillStackAI</span> generate documentation with intelligent context instantly.
            </motion.p>
            <FileUpload onUploadSuccess={setDoc} />
            {error && <div className="mt-4 p-3 bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-lg text-center">{error}</div>}
          </div>
        </motion.div>

        {/* Right Panel - Generated Documentation */}
        <motion.div
          className="w-full lg:w-8/12 flex flex-col h-[calc(100vh-140px)] min-h-[600px] pb-6"
          initial={{ opacity: 0, x: 30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <ActionButtons 
            doc={doc}
            isGeneratingPdf={isGeneratingPdf}
            onExportMarkdown={handleExportMarkdown}
            onDownloadPdf={handleDownloadPdf}
            onCopy={handleCopy}
            onShare={handleShare}
          />
          <OutputContainer doc={doc} />
        </motion.div>
      </div>

      {doc && (
        <div style={{ position: 'absolute', top: '-9999px', left: '-9999px', width: '800px', backgroundColor: 'white' }}>
          <div id="pdf-export-container" className="pdf-markdown-content" style={{ fontFamily: 'Arial, Helvetica, sans-serif', padding: '10px 20px', backgroundColor: 'white', color: '#1f2937' }}>
            <style dangerouslySetInnerHTML={{
              __html: `
                .pdf-markdown-content { background-color: white !important; color: #1f2937 !important; }
                .pdf-markdown-content h1 { color: #8A4FFF !important; font-size: 2rem !important; font-weight: 700 !important; margin-bottom: 20px !important; margin-top: 24px !important; border-bottom: 2px solid #8A4FFF !important; padding-bottom: 8px !important; page-break-after: avoid; }
                .pdf-markdown-content h2 { color: #6d28d9 !important; font-size: 1.5rem !important; font-weight: 700 !important; margin-bottom: 16px !important; margin-top: 24px !important; page-break-after: avoid; }
                .pdf-markdown-content h3 { color: #374151 !important; font-size: 1.25rem !important; font-weight: 600 !important; margin-bottom: 12px !important; margin-top: 20px !important; page-break-after: avoid; }
                .pdf-markdown-content p { font-size: 11pt !important; line-height: 1.6 !important; color: #374151 !important; margin-bottom: 16px !important; }
                .pdf-markdown-content ul, .pdf-markdown-content ol { margin-bottom: 16px !important; padding-left: 24px !important; }
                .pdf-markdown-content li { font-size: 11pt !important; line-height: 1.6 !important; color: #374151 !important; margin-bottom: 6px !important; }
                .pdf-markdown-content pre { background-color: #f3f4f6 !important; border: 1px solid #d1d5db !important; border-radius: 8px !important; padding: 16px !important; margin: 20px 0 !important; page-break-inside: avoid !important; white-space: pre-wrap !important; word-wrap: break-word !important; }
                .pdf-markdown-content code { color: #047857 !important; font-family: 'Courier New', Courier, monospace !important; font-size: 9.5pt !important; }
                .pdf-markdown-content table { width: 100% !important; border-collapse: collapse !important; margin: 20px 0 !important; page-break-inside: avoid !important; }
                .pdf-markdown-content th, .pdf-markdown-content td { border: 1px solid #d1d5db !important; padding: 12px !important; text-align: left !important; }
                .pdf-markdown-content th { background-color: #f3f4f6 !important; color: #374151 !important; font-weight: 700 !important; }
                .pdf-markdown-content blockquote { border-left: 4px solid #8A4FFF !important; padding-left: 16px !important; color: #4b5563 !important; font-style: italic !important; background-color: #f9fafb !important; padding: 16px !important; margin: 20px 0 !important; page-break-inside: avoid !important; }
              `
            }} />
            <ReactMarkdown>{doc.content || doc}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  );
}
