"use client";

import React, { useState } from "react";
import { FaFilePdf, FaCopy, FaShareAlt, FaEye, FaTrash } from "react-icons/fa";
import toast from "react-hot-toast";

export default function DocumentRow({ doc, onDelete }) {
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const token = typeof window !== 'undefined' ? localStorage.getItem("token") : null;

  const handleDelete = async (e) => {
    e.stopPropagation();
    if (!window.confirm("Are you sure you want to delete this document?")) return;
    
    setIsDeleting(true);
    try {
      const response = await fetch(`http://localhost:5000/api/docs/${doc._id}`, {
        method: 'DELETE',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      
      if (!response.ok) throw new Error("Failed to delete document");
      
      toast.success("Document deleted permanently");
      if (onDelete) onDelete(doc._id);
    } catch (err) {
      toast.error("Failed to delete document");
      setIsDeleting(false); // Only reset if failed. If success, component unmounts instantly.
    }
  };

  // Fallback missing properties gracefully
  const title = doc.filename || "Untitled Document";
  const language = doc.language || "Unknown";
  
  // Custom date formatter using native JS
  const formatDate = (dateString) => {
    if (!dateString) return "Recently";
    const d = new Date(dateString);
    return d.toLocaleString('en-US', { 
      month: 'short', day: 'numeric', year: 'numeric', 
      hour: 'numeric', minute: '2-digit', hour12: true 
    });
  };
  
  const date = formatDate(doc.generatedAt);
  const previewText = doc.content ? doc.content.substring(0, 150) + "..." : "No preview available.";
  
  const handleView = () => {
    window.open(`/doc/${doc._id}`, '_blank');
  };

  const handleCopy = () => {
    if (!doc.content) return;
    navigator.clipboard.writeText(doc.content)
      .then(() => toast.success("Copied to clipboard!"))
      .catch(() => toast.error("Failed to copy"));
  };

  const handleShare = async () => {
    const shareUrl = `${window.location.origin}/doc/${doc._id}`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: `QuillStack AI - ${title}`,
          text: 'Check out this generated documentation!',
          url: shareUrl,
        });
        return;
      } catch (err) {
        if (err.name === "AbortError") return;
      }
    }
    navigator.clipboard.writeText(shareUrl)
      .then(() => toast.success("Share link copied!"))
      .catch(() => toast.error("Failed to copy link"));
  };

  const handleDownloadPdf = async () => {
    setIsGeneratingPdf(true);
    try {
      const html2pdf = (await import('html2pdf.js')).default;
      
      const element = document.createElement('div');
      element.innerHTML = `<div class="pdf-markdown-content" style="font-family: Arial, Helvetica, sans-serif; padding: 10px 20px; background-color: white; color: #1f2937;">${doc.content.replace(/\n/g, '<br>')}</div>`;
      document.body.appendChild(element);

      const opt = {
        margin: [20, 15, 20, 15],
        filename: `${title.replace(/[^a-z0-9]/gi, '_')}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
      };

      const worker = html2pdf().from(element).set(opt);
      await worker.toPdf().get('pdf').then((pdf) => {
        const totalPages = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          pdf.setFontSize(10);
          pdf.setTextColor(100);
          pdf.text('QuillStack AI Documentation', 15, 12);
          pdf.setDrawColor(200);
          pdf.setLineWidth(0.5);
          pdf.line(15, 15, pdf.internal.pageSize.getWidth() - 15, 15);
          pdf.line(15, pdf.internal.pageSize.getHeight() - 15, pdf.internal.pageSize.getWidth() - 15, pdf.internal.pageSize.getHeight() - 15);
          pdf.text('Generated by QuillStack AI', 15, pdf.internal.pageSize.getHeight() - 10);
          pdf.text(`Page ${i} of ${totalPages}`, pdf.internal.pageSize.getWidth() - 35, pdf.internal.pageSize.getHeight() - 10);
        }
      });
      await worker.save();
      
      document.body.removeChild(element);
      toast.success("PDF Downloaded!");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate PDF");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className="group flex flex-col sm:flex-row items-start sm:items-center justify-between p-5 bg-[#181C2A] border border-gray-800 hover:border-fuchsia-500/40 rounded-xl hover:bg-[#1E2335] shadow-sm hover:shadow-[0_4px_20px_rgba(138,79,255,0.1)] transition-all duration-300 w-full">
      {/* Left Section: Info */}
      <div 
        className="flex-1 cursor-pointer pr-0 sm:pr-6 w-full sm:w-auto mb-4 sm:mb-0" 
        onClick={handleView}
      >
        <div className="flex items-center gap-3 mb-2">
          <h3 className="text-lg font-bold text-white group-hover:text-fuchsia-400 transition-colors line-clamp-1" title={title}>
            {title}
          </h3>
          <span className="bg-fuchsia-700/20 text-fuchsia-300 text-[10px] px-2.5 py-0.5 rounded-full border border-fuchsia-700/30 whitespace-nowrap">
            {language}
          </span>
        </div>
        
        <p className="text-sm text-gray-400 line-clamp-2 mb-3 max-w-4xl">
          {previewText}
        </p>
        
        <div className="flex items-center text-xs text-gray-500">
          <svg className="w-3.5 h-3.5 mr-1.5 opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
          {date}
        </div>
      </div>

      {/* Right Section: Actions */}
      <div className="flex flex-wrap sm:flex-nowrap items-center gap-2 sm:ml-4 w-full sm:w-auto justify-end sm:justify-start border-t sm:border-t-0 border-gray-800 pt-4 sm:pt-0">
        <button onClick={(e) => { e.stopPropagation(); handleView(); }} className="p-2.5 rounded-lg bg-gray-800/80 hover:bg-fuchsia-700/20 text-gray-300 hover:text-fuchsia-400 transition-colors border border-transparent hover:border-fuchsia-700/30 flex items-center justify-center" title="View Full Document">
          <FaEye className="text-[16px]" />
        </button>
        <button onClick={(e) => { e.stopPropagation(); handleDownloadPdf(); }} disabled={isGeneratingPdf} className="p-2.5 rounded-lg bg-gray-800/80 hover:bg-fuchsia-700/20 text-gray-300 hover:text-fuchsia-400 transition-colors border border-transparent hover:border-fuchsia-700/30 disabled:opacity-50 flex items-center justify-center" title="Download PDF">
          <FaFilePdf className="text-[16px]" />
        </button>
        <button onClick={(e) => { e.stopPropagation(); handleCopy(); }} className="p-2.5 rounded-lg bg-gray-800/80 hover:bg-fuchsia-700/20 text-gray-300 hover:text-fuchsia-400 transition-colors border border-transparent hover:border-fuchsia-700/30 flex items-center justify-center" title="Copy Content">
          <FaCopy className="text-[16px]" />
        </button>
        <button onClick={(e) => { e.stopPropagation(); handleShare(); }} className="p-2.5 rounded-lg bg-gray-800/80 hover:bg-fuchsia-700/20 text-gray-300 hover:text-fuchsia-400 transition-colors border border-transparent hover:border-fuchsia-700/30 flex items-center justify-center" title="Share Link">
          <FaShareAlt className="text-[16px]" />
        </button>
        <button onClick={handleDelete} disabled={isDeleting} className="p-2.5 rounded-lg bg-gray-800/80 hover:bg-red-500/20 text-gray-300 hover:text-red-400 transition-colors border border-transparent hover:border-red-500/30 disabled:opacity-50 flex items-center justify-center sm:ml-2" title="Delete Document">
          <FaTrash className="text-[16px]" />
        </button>
      </div>
    </div>
  );
}
